# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MLASMaintenance
                                 A QGIS plugin
 MLAS Data maintenance plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-01
        copyright            : (C) 2021 by LeveeLogic
        email                : breinbaasnl@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MLASMaintenance class from file MLASMaintenance.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mlas_maintenance import MLASMaintenance
    return MLASMaintenance(iface)
